<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle nav_btn"><span>Toggle Nav</span></span>
<?php if ($block->isHomePage()):?>
    <strong class="logo"><a href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"             
        />
<?php if ($block->isHomePage()):?>
    </a></strong>
<?php else:?>
    </a>
<?php endif?>