<div class="homepage-content">
    <?php echo $this->getChildHtml('product.list'); ?>

    <div class="bootstrap-container">
        <div class="bootstrap-row homepage-terms-row">
            <div class="col bootstrap-col"><strong>Delivery Date:</strong>  Within 4 days</div>
            <div class="col bootstrap-col"><strong>Payment Terms:</strong>  Net 30</div>
            <div class="col bootstrap-col"><strong>Shipping Method:</strong>  UPS</div>
            <div class="col bootstrap-col"><strong>Shipping Terms:</strong>  FOB Warehouse Jacksonville FL</div>
        </div>
        <br>
        <div class="bootstrap-row">
            <div class="col bootstrap-col homepage-terms">
                <p><strong>Terms & Conditions:</strong></p>
                <ul>
                    <li>A Return Authorization Number (RMA) is required on all returns.  The RMA can only be issued within 30 days of the original ship date.</li>
                    <li>Merchandise returned which is tested functional and without defect will be subject to a minimum processing fee of 15% of the product price.</li>
                    <li>Return of defective or mis-picked items are limited to exchanges only.</li>
                    <li>Sales tax will be charged where applicable unless a tax-exempt certificate is on file.</li>
                    <li>Shipping charges are contingent on quantity orders, total weight of products and the unusual size.</li>
                    <li>This offer is contingent on quantity restrictions and is subject to product availability.</li>
                    <li>We reserve the right to review this quote in the event of a market price increase.</li>
                </ul>
            </div>
        </div>
    </div>
</div>