<?php
$_helper = $this->helper('WeltPixel\LazyLoading\Helper\Data');
$imageLoader = $_helper->getImageLoader();
?>
<script type="text/javascript">
    require(['jquery', 'WeltPixel_LazyLoading/js/lazy'], function($) {
        $(document).ready(function () {
            $(".lazy").lazy({
                attribute: 'data-original',
                visibleOnly: false,
            });
        });

        $('body').on('loadMenu',function(e) {
            $('nav.navigation .lazy').lazy({
                attribute: 'data-original',
                visibleOnly: false,
            });
        });
    });
</script>