<?php
$currentShippingInfo = $block->getTrackingData();
$_results = $currentShippingInfo->getTrackingInfo();
?>
<div class="page tracking">
    <?php if (sizeof($_results)>0) : ?>
    <?php foreach ($_results as $shipid => $_result) : ?>
        <?php if ($shipid) : ?>
        <div class="order subtitle caption"><?php /* @noEscape */ echo __('Shipment #') . $shipid; ?></div>
        <?php endif; ?>
        <?php if (sizeof($_result)>0) : ?>
            <?php $rowCount = sizeof($_result);
                  $counter = 1;
                  $_id = 0;
            foreach ($_result as $track) : ?>
                <div class="table-wrapper">
                    <table class="data table order tracking"
                    id="tracking-table-popup-<?php /* @noEscape */ echo $_id ?>">
                        <caption class="table-caption"><?php /* @noEscape */ echo __('Order tracking'); ?></caption>
                        <tbody>
                        <?php if (is_object($track)) : ?>
                            <tr>
                                <th class="col label" scope="row" width="30%">
                                <?php /* @noEscape */ echo __('Tracking Number:'); ?></th>
                                <td class="col value" width="70%">
                                <?php echo $block->escapeHtml($track->getTracking()); ?></td>
                            </tr>
                            <?php if ($track->getCarrierTitle()) : ?>
                                <tr>
                                    <th class="col label" scope="row" width="30%">
                                    <?php /* @noEscape */ echo __('Carrier:'); ?></th>
                                    <td class="col value" width="70%">
                                    <?php echo $block->escapeHtml($track->getCarrierTitle()); ?></td>
                                </tr>
                            <?php endif; ?>
                            <?php if ($track->getErrorMessage()) : ?>
                                <tr>
                                    <th class="col label" scope="row" width="30%"><?php /* @noEscape */ echo __('Error:'); ?></th>
                                    <td class="col error" width="70%">
                                    <?php /* @noEscape */ echo __('Tracking information is currently not available.
                                    Please ');
                                    if ($block->getContactUsEnabled()) : ?>
                                            <a href="<?php /* @noEscape */ echo $block->getContactUs() ?>"
                                            title="<?php /* @noEscape */ echo __('contact us') ?>" 
                                            onclick="this.target='_blank'">
                                                <?php /* @noEscape */ echo __('contact us') ?>
                                            </a>
                                        <?php /* @noEscape */ echo __(' for more information or ');
                                    endif;
                                        /* @noEscape */ echo __('email us at '); ?>
                                        <a href="mailto:<?php /* @noEscape */ echo $block->getStoreSupportEmail() ?>">
                                        <?php /* @noEscape */ echo $block->getStoreSupportEmail() ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php elseif ($track->getTrackSummary()) : ?>
                                <tr>
                                    <th class="col label" scope="row" width="30%">
                                    <?php /* @noEscape */ echo __('Info:'); ?></th>
                                    <td class="col value" width="70%">
                                    <?php /* @noEscape */ echo $track->getTrackSummary(); ?></td>
                                </tr>
                            <?php elseif ($track->getUrl()) : ?>
                                <tr>
                                    <th class="col label" scope="row" width="30%">
                                    <?php /* @noEscape */ echo __('Track:'); ?></th>
                                    <td class="col value" width="70%">
                                        <a href="<?php echo $block->escapeHtml($track->getUrl()); ?>" 
                                        onclick="this.target='_blank'">
                                            <?php echo $block->escapeHtml($track->getUrl()); ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php else : ?>
                                <?php if ($track->getStatus()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                        <?php /* @noEscape */ echo __('Status:'); ?></th>
                                        <td class="col value" width="70%">
                                        <?php /* @noEscape */ echo $track->getStatus(); ?></td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getDeliverydate()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                        <?php /* @noEscape */ echo __('Delivered on:'); ?></th>
                                        <td class="col value" width="70%">
                                        <?php /* @noEscape */ echo $block->formatDeliveryDateTime($track
                                        ->getDeliverydate(), $track->getDeliverytime()); ?></td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getSignedby()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                        <?php /* @noEscape */ echo __('Signed by:'); ?></th>
                                        <td class="col value" width="70%">
                                        <?php /* @noEscape */ echo $track->getSignedby(); ?></td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getDeliveryLocation()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                        <?php /* @noEscape */ echo __('Delivered to:'); ?></th>
                                        <td class="col value" width="70%">
                                        <?php /* @noEscape */ echo $track->getDeliveryLocation(); ?></td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getShippedDate()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                            <?php /* @noEscape */ echo __('Shipped or billed on:'); ?>
                                        </th>
                                        <td class="col value" width="70%">
                                            <?php /* @noEscape */ echo $track->getShippedDate(); ?>
                                        </td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getService()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                            <?php /* @noEscape */ echo __('Service Type:'); ?>
                                        </th>
                                        <td class="col value" width="70%"><?php /* @noEscape */ echo $track->getService(); ?></td>
                                    </tr>
                                <?php endif; ?>

                                <?php if ($track->getWeight()) : ?>
                                    <tr>
                                        <th class="col label" scope="row" width="30%">
                                            <?php /* @noEscape */ echo __('Weight:'); ?>
                                        </th>
                                        <td class="col value" width="70%"><?php /* @noEscape */ echo $track->getWeight(); ?></td>
                                    </tr>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php elseif (isset($track['title']) && isset($track['number']) && $track['number']) : ?>
                            <?php /* if the tracking is custom value */ ?>
                            <tr>
                                <th class="col label" scope="row" width="30%"><?php /* @noEscape */ echo($track['title'] ?
                                $block->escapeHtml($track['title']) : __('N/A')); ?>:</th>
                                <td class="col value" width="70%">
                                    <?php echo(isset($track['number']) ? $block->escapeHtml($track['number']) : ''); ?>
                                </td>
                            </tr>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
                <?php if (is_object($track) && sizeof($track->getProgressdetail())>0) : ?>
                    <div class="table-wrapper">
                        <table class="data table order tracking"
                        id="track-history-table-<?php /* @noEscape */ echo $track->getTracking(); ?>">
                            <caption class="table-caption"><?php /* @noEscape */ echo __('Track history'); ?></caption>
                            <thead>
                            <tr>
                                <th class="col location" scope="col"><?php /* @noEscape */ echo __('Location') ?></th>
                                <th class="col date" scope="col"><?php /* @noEscape */ echo __('Date') ?></th>
                                <th class="col time" scope="col"><?php /* @noEscape */ echo __('Local Time') ?></th>
                                <th class="col description" scope="col">
                                    <?php /* @noEscape */ echo __('Description') ?>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($track->getProgressdetail() as $_detail) : ?>
                                <?php $_detailDate = (isset($_detail['deliverydate']) ?
                                $block->formatDeliveryDate($_detail['deliverydate']) : '') ?>
                                <?php $_detailTime = (isset($_detail['deliverytime']) ?
                                $block->formatDeliveryTime($_detail['deliverytime'], $_detail['deliverydate']) : '') ?>
                                <tr>
                                    <td data-th="<?php /* @noEscape */ echo $block->escapeHtml(__('Location')) ?>"
                                    class="col location">
                                    <?php /* @noEscape */ echo(isset($_detail['deliverylocation']) ?
                                    $_detail['deliverylocation'] : ''); ?></td>
                                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date">
                                    <?php /* @noEscape */ echo $_detailDate ?></td>
                                    <td data-th="<?php echo $block->escapeHtml(__('Local Time')) ?>" 
                                    class="col time"><?php /* @noEscape */ echo $_detailTime ?></td>
                                    <td data-th="<?php echo $block->escapeHtml(__('Description')) ?>"
                                    class="col description">
                                    <?php /* @noEscape */ echo(isset($_detail['activity']) ?
                                    $_detail['activity'] : '') ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
                <?php if ($counter != $rowCount) : ?>
                <?php endif; ?>
                <?php $counter++; ?>
            <?php /* end for each tracking information */ ?>
            <?php endforeach; ?>
        <?php else : ?>
            <div class="message info empty">
                <div>
                    <?php /* @noEscape */ echo __('There is no tracking available for this shipment.'); ?>
                </div>
            </div>
        <?php endif; ?>

    <?php endforeach; ?>
    <?php else : ?>
        <div class="message info empty">
            <div>
                <?php /* @noEscape */ echo __('There is no tracking available.'); ?>
            </div>
        </div>
    <?php endif; ?>


    <?php

            $data = $this->getRequest()->getParams();
            $orderId = $data["order"];
            $email = $data["postcode"];

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$orderDatamodel = $objectManager->get('Magento\Sales\Model\Order')->getCollection();
$orderDatamodel->addAttributeToFilter('increment_id',array('eq'=>$orderId));
$orderProductData = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($orderId);
 $orderProductData->getStatusLabel();



$items = $orderProductData->getAllItems();
?>
<div class="order-status-sec">
<div class="inner-status-sec">
<?php

//echo "<pre/>";
foreach ($orderDatamodel as $collection)
{
    $ordervar = $collection->getBillingAddress();
    //echo "Order #:" .$collection->getIncrementId().'<br/>';
    $ordervar1 = $collection->getShippingAddress();
    //echo $ordervar1->getShippingMethod();
    
    ?>
    
    <div class="order-status-number">
        <span>Order #:</span>
        <?php echo $collection->getIncrementId(); ?>
    </div>
    <div id="ship-to">
    <div class="order-shipment-title"><span>Ship To:</span></div>
    <div id="ship-to-fields">
        <table>
            <tbody>
            <tr>
                <th>Name:</th>
                <td>
                    <?php echo $ordervar->getFirstname().' '.$ordervar->getFirstname();  ?>
                </td>
            </tr>
            <tr>
                <th>Email Address:</th>
                <td><?php echo $collection->getCustomerEmail(); ?></td>
            </tr>
            <?php if($ordervar1['telephone'] != NULL) { ?>
            <tr>
                <th>Phone Number:</th>
                <td><?php echo $ordervar1['telephone']; ?></td>
            </tr>
            <?php } ?>
            <?php if($ordervar1['company'] != NULL) { ?>
            <tr>
                <th>Company:</th>
                <td><?php echo $ordervar1['company']; ?></td>
            </tr>
            <?php } ?>
            <?php if($ordervar1['street'] != NULL) { ?>
            <tr>
                <th>Address:</th>
                <td><?php echo $ordervar1['street']; ?></td>
            </tr>
            <?php } ?>
        </tbody>
        </table>
    </div>
    </div>


    <div id="bill-to">
    <div class="order-bill-title"><span>Bill To:</span></div>
    <div id="ship-to-fields">
        <table>
            <tbody>
            <tr>
                <th>Name:</th>
                <td>
                    <?php echo $ordervar1->getFirstname().' '.$ordervar->getFirstname();  ?>
                </td>
            </tr>
            <tr>
                <th>Email Address:</th>
                <td><?php echo $collection->getCustomerEmail(); ?></td>
            </tr>
            <?php if($ordervar['telephone'] != NULL) { ?>
            <tr>
                <th>Phone Number:</th>
                <td><?php echo $ordervar['telephone']; ?></td>
            </tr>
            <?php } ?>
            <?php if($ordervar['company'] != NULL) { ?>
            <tr>
                <th>Company:</th>
                <td><?php echo $ordervar['company']; ?></td>
            </tr>
            <?php } ?>
            <?php if($ordervar['street'] != NULL) { ?>
            <tr>
                <th>Address:</th>
                <td><?php echo $ordervar['street']; ?></td>
            </tr>
            <?php } ?>
        </tbody>
        </table>    
    
    </div>
    </div>
    <?php
}

?>
    </div>
<?php
//image,name,sku,discount amt,type of product | Quantity | Price | Subtotal |
foreach($items as $item)
{ 

$hotPrd = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getData('product_id'));
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
 $product_image = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $hotPrd->getImage();

?>
<div class="column whole medium-two-thirds cart-contents">
<div class="item-table">
<table>
    <thead>
        <tr>
            <th class="col item">Product</th>
            <th class="col qty">Quantity</th>
            <th class="col status">Status</th>
            <th class="col price">Price</th>
            <th class="col total">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="col item" data-th="Product">
                <div class="pro-image">
                    <img src="<?php echo $product_image ?>">
                </div>
                <div class="pro-item-detail">
                    <?php echo $item->getName(); ?>
                </div>
            </td>
            <td class="col qty" data-th="Quantity">
                 <?php echo number_format((float)$item->getQtyOrdered()); ?>
                 <?php echo $item->getQauntity(); ?>
            </td>
            <td class="col status" data-th="Status"><?php echo $orderProductData->getStatusLabel();//echo $item->getProductType(); ?></td>
            <td class="col price" data-th="Price">
                $<?php echo number_format((float)$item->getOriginalPrice(),2); ?>
            </td>
            <td class="col total" data-th="Subtotal">
               $<?php echo number_format((float)$item->getBaseRowTotal(),2); ?>
            </td>
        </tr>
    </tbody>
</table>
</div>
<div class="cart-total">
    <h2>Cart Summary</h2>
    <p><strong>Discount:</strong> $<?php echo number_format((float)$item->getDiscountAmount(),2);?></p>
    <p><strong>Shipping Price:</strong> $<?php echo number_format((float)$orderProductData->getShippingAmount(),2); ?></p>
    <p><strong>Sales Tax:</strong> $<?php echo number_format((float)$item->getTaxAmount(),2); ?></p>
    <p><strong>Total:</strong> $<?php echo number_format((float)$orderProductData->getGrandTotal(),2);?></p>

</div>
</div>



<?php } ?>

</div>