<!--**********************************************-->
<!--***** BEGIN GOOGLE UNIVERSAL ANALYTICS *******-->
<!--**********************************************-->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-388020-1', 'auto', {
  'allowLinker': true
})
ga('require', 'linkid');
ga('require', 'linker');
ga('linker:autoLink', ['pospaper.com', 'yahoo.net'], true, false);
ga('require', 'ec');
ga('require', 'GTM-M5W5PD6');
ga('send', 'pageview');
</script>
<!--**********************************************-->
<!--******* END GOOGLE UNIVERSAL ANALYTICS *******-->
<!--**********************************************-->