<div class="middle-container">
    <?php $homepageBanners = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_banners')->toHtml(); ?>
    <?php if($homepageBanners): ?>
    <div class="homepage-banners-container">
        <div class="container">
            <div class="homepage-banners">
                <?php echo $homepageBanners; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php $homepageSeo = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_seo')->toHtml(); ?>
    <?php if($homepageSeo): ?>
    <div class="homepage-content">
        <div class="container"><?php echo $homepageSeo; ?></div>
    </div>
    <?php endif; ?>

    <div class="category-section">
        <div class="container">
        <?php echo $this->getLayout()->createBlock("Pos\Custommodule\Block\Poscategory")->setTemplate("Pos_Custommodule::home_category.phtml")->toHtml(); ?>
        </div>
    </div>

    <div class="home-tabing-div">
        <div class="container">
            <div id="parentHorizontalTab">
                 <ul class="resp-tabs-list hor_1">
                    <li><?php echo __("Top Selling Products"); ?></li>
                    <li><?php echo __("Featured Products"); ?></li>
                </ul>
                <div class="resp-tabs-container hor_1">
                    <div id="best-seller" class="tabcontent">
                        <?php echo $this->getChildHtml('homepage.bestsellers') ?>
                    </div>
                    <div id="featured-products" class="tabcontent">
                        <?php echo $this->getChildHtml('homepage.featured') ?>
                    </div>
                </div>
            </div>
       </div>
    </div>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('why_shop_block')->toHtml();?>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('happy_customer_section')->toHtml();?>
</div>



<script type="text/javascript">
    jQuery(document).ready(function() {
        //Horizontal Tab
       jQuery('#parentHorizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true, // 100% fit in a container
            tabidentify: 'hor_1', // The tab groups identifier
            activate: function(event) { // Callback function if tab is switched
                var $tab = jQuery(this);
                var $info = jQuery('#nested-tabInfo');
                var $name = jQuery('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });
    });
</script>
