<div class="middle-container">
    <?php $homepageBanners = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_banners')->toHtml(); ?>
    <?php if($homepageBanners): ?>
    <div class="homepage-banners-container">
        <div class="container">
            <div class="homepage-banners">
                <div class="col-left">
                    <div class="title-1">Check out our New,</div>
                    <div class="title-2">Lower Prices!!!</div>
                    <div class="sub-title">The Highest Quality <a href="https://www.pospaper.com/thermal-paper-rolls/all-thermal-paper.html">Thermal</a>, <a href="https://www.pospaper.com/bond-carbonless-paper-rolls.html">Bond & Carbonless Paper Rolls</a> backed by our <strong>Low Price Guarantee!</strong></div>
                    <img src="<?php echo $block->getViewFileUrl('images/banner-icon.png') ?>" alt="1 – 3 day Shipping to most of the USA!" />
                    <p>1 – 3 day Shipping to most of the USA!</p>
                </div>
                <div class="col-right">
                    <div class="title">Check out our <strong>BEST SELLERS...</strong></div>
                    <ul>
                        <li><a href="https://www.pospaper.com/3-1-8-x-230-thermal-paper-50-rolls.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-1-2.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/3-1-8-x-220-thermal-paper-50-rolls.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-2-2-2.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/2-1-4-x-50-thermal-paper-50-rolls.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-3-2.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/2-1-4-x-85-thermal-paper-50-rolls.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-4-2.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/3-x-95-2-ply-carbonless-paper-50-rolls-white-canary.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-5.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/3-x-165-1-ply-bond-paper-50-rolls.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-6.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/epson-erc-30-34-38-printer-ribbons-6-per-box-black-red.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-7.png') ?>" alt="" /></a></li>
                        <li><a href="https://www.pospaper.com/restaurant-crayons.html"><img src="<?php echo $block->getViewFileUrl('images/banners/product-8.png') ?>" alt="" /></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php $homepageSeo = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_seo')->toHtml(); ?>
    <?php if($homepageSeo): ?>
    <div class="homepage-content">
        <div class="container"><?php echo $homepageSeo; ?></div>
    </div>
    <?php endif; ?>

    <div class="category-section">
        <div class="container">
        <?php echo $this->getLayout()->createBlock("Pos\Custommodule\Block\Poscategory")->setTemplate("Pos_Custommodule::home_category.phtml")->toHtml(); ?>
        </div>
    </div>

    <div class="home-tabing-div">
        <div class="container">
            <div id="parentHorizontalTab">
                 <ul class="resp-tabs-list hor_1">
                    <li><?php echo __("Top Selling Products"); ?></li>
                    <li><?php echo __("Featured Products"); ?></li>
                </ul>
                <div class="resp-tabs-container hor_1">
                    <div id="best-seller" class="tabcontent">
                        <?php echo $this->getChildHtml('homepage.bestsellers') ?>
                    </div>
                    <div id="featured-products" class="tabcontent">
                        <?php echo $this->getChildHtml('homepage.featured') ?>
                    </div>
                </div>
            </div>
       </div>
    </div>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('why_shop_block')->toHtml();?>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('happy_customer_section')->toHtml();?>
</div>



<script type="text/javascript">
    jQuery(document).ready(function() {
        //Horizontal Tab
       jQuery('#parentHorizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true, // 100% fit in a container
            tabidentify: 'hor_1', // The tab groups identifier
            activate: function(event) { // Callback function if tab is switched
                var $tab = jQuery(this);
                var $info = jQuery('#nested-tabInfo');
                var $name = jQuery('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });
    });
</script>
