<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */
?>

 
 <!-- <a class='weltpixel-quickview weltpixel_quickview_button_v2' title="Quick View" onclick ="newwin('<?php echo $block->getBaseUrl()?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->getProduct()->getId()?>')"  data-quickview-url='<?php echo $block->getBaseUrl()?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->getProduct()->getId()?>' href='javascript:void(0);'>                           
 <span>Quickview</span>
 </a> -->
 
  <a class='weltpixel-quickview weltpixel_quickview_button_v2' title="Quick View" data-quickview-url='<?php echo $block->getBaseUrl()?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->getProduct()->getId()?>' href='javascript:void(0);'>                           
 <span>Quickview</span>
 </a>
 
<a href="#"
   class="action tocompare"
   title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
   data-post='<?= /* @escapeNotVerified */ $block->getCompareHelper()->getPostDataParams($block->getProduct()) ?>'
   role="button">
    <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
</a>
