<div class="detail-shipping-div">
    <div class="metric-div">
        <ul>
            <li class="price"><a id="price-match" href="/price-match/price-match.php"> Low Price Guarantee <span>We won't be beat on price</span> </a></li>
        </ul>
    </div>
    <span class="tooltip-text">Our Low Price Guarantee includes the price of the item(s) plus shipping cost. Items must be available from competitor to ship to customer’s location and be viewable online.</span>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function($){
        $('#price-match').fancybox({
            'type' : 'iframe'
        });
    });
</script>