<div class="detail-shipping-div">
    <div class="metric-div">
        <ul>
            <li><a id="free-shipping" href="#"><img src="<?php echo $this->getViewFileUrl('images/free-shipping-icon.png'); ?>" alt="" /></a></li>
        </ul>
    </div>
    <span class="tooltip-text">Free Ground Shipping for all orders of $50 (USD) or more shipped within the contiguous United States.</span>
</div>
<div class="detail-shipping-div">
    <div class="metric-div">
        <ul>
            <li class="price"><a id="price-match" href="#"> Low Price Guarantee <span>We won't be beat on price</span> </a></li>
        </ul>
    </div>
    <span class="tooltip-text">Our Low Price Guarantee includes the price of the item(s) plus shipping cost. Items must be available from competitor to ship to customer’s location and be viewable online.</span>
</div>
