<?php $products = $block->getProductCollection(); ?>
<?php if(count($products)): ?>
<div id="best-slider" class="homepage-product-slider-grid">
<?php foreach ($products as $product): ?>
    <?php $productImage = $block->getImage($product, 'review_page_product_image'); ?>
    <div class='item'>
        <div class="item-wrapper">
            <a class="slider-pro-img" href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>"><img src="<?php echo $productImage->getImageUrl() ?>" class="lazy" /></a>
            <div class='slider-produc-info'>
                <div class='main_bestseller_name slider-pro-name'>
                    <a href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>"><?php echo $block->getProductName($product->getName()) ?></a>
                </div>
                <div class='main_bestseller_price slider-price'>
                    <div class="price-div">
                        <?php
                        if ($product->getTierPrice()) {
                            $tier_prices = $product->getTierPrice();
                            foreach ($tier_prices as $price) {
                                $website_price = $price['website_price'];
                            };
                            $bsprice = '<span class="price-label">As low as</span>' . $this->getFormatedPrice($website_price);
                        } else {
                            $bsprice = $this->getFormatedPrice($product->getFinalPrice());
                        }
                        echo $bsprice;
                        echo '/' . $product->getData('unit_of_measure');
                        ?>
                    </div>
                    <div class='rating-div'>
                    <?php
                    $_ratingSummary = $block->getRatingSummary($product);
                    $_reviewCount = $product->getRatingSummary()->getReviewsCount();
                    ?>
                    <?php if ($_ratingSummary): ?>
                        <div class="product-reviews-summary short">
                            <div class="rating-summary">
                                <div title="<?php echo (int)$_ratingSummary; ?>%" class="rating-result">
                                    <span style="width:<?php echo (int)$_ratingSummary; ?>%"><span><?php echo (int)$_ratingSummary; ?>%</span></span>
                                </div>
                            </div>
                            <div class="reviews-actions">
                                <?php echo __('(' . $_reviewCount . ')'); ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class='slider-button-sec'>
                <div class='main_bestseller_addto'>
                    <form data-role='tocart-form' action='<?php echo $this->getAddToCartUrl($product) ?>' method='post'>
                        <?php echo $block->getBlockHtml('formkey') ?>
                        <button type='submit'
                                title='Add to Cart'
                                class='action tocart primary'>
                            <span>Add to Cart</span>
                        </button>
                    </form>
                </div>
                <div class='main_featured_quickview other-actions'>
                    <a class='action whishlist towishlist' href='#' data-action='add-to-wishlist' data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product)?> '><span>Whishlist</span></a>
                    <a class='action tocompare' href='#' data-post='<?php echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($product) ?>' role='button'><span>Compare</span></a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?php echo $product->getSku(); ?>"
            }
        }
    }
    </script>
<?php endforeach; ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>
<?php endif; ?>