<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>
<?php if ($exist):?>
    <div class="block widget recently block-viewed-products-<?= /* @escapeNotVerified */ $mode ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
        </div>
        <div class="block-content">
            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                <ol class="product-items <?= /* @escapeNotVerified */ $type ?> recently-slider owl-carousel">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                        
                            <div class="product-image">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                            </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-link">
                                        
                                        <?php /* @escapeNotVerified */ 
                                    $str = $block->escapeHtml($_item->getName());
                                   // $tmp_str = mb_substr($str,0,111,'utf-8');
                                  echo $out = strlen($str) > 104 ? substr($str,0,104)."..." : $str;
                                    /*if(strlen($str) > 110)
                                    {
                                        echo $str."..." ;
                                    }
                                    else
                                    {
                                        echo $str;
                                    }*/
                                    
                                 ?>
                                    </a>
                                </strong>
                                <div class="pro-price">


                                    <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    if($_item->getTierPrice())
                    {
                        $tier_prices = $_item->getTierPrice();
                        foreach ($tier_prices as $price) {
                        $website_price = $price['website_price'];
                        };
                        $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
                        $bsprice = '<span class="price-label">As low as</span><span class="price">'.$priceHelper->currency($website_price, true, false).'</span>';
                    }
                    else
                    {
                     $bsprice = $_item->getFormatedPrice($_item->getFinalPrice());    
                    }
                    echo $bsprice;
             $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
             echo '/'.$product->getData('unit_of_measure'); 
            ?>

                               
                                <?php if ($rating): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $rating) ?>
                                <?php endif; ?>
                                </div> 
                                <?php
                        
                        if ($_item->getData('is_bestseller') == 1): ?>
                    <div class="bestseller-img">
                    put image here
                    </div>
                        <?php endif;?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                                       title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
    <a class='weltpixel-quickview weltpixel_quickview_button_v2' data-quickview-url='<?php echo $block->getBaseUrl()?>weltpixel_quickview/catalog_product/view/id/<?php echo $_item->getId()?>' href='javascript:void(0);'>    
    <span>Quickview</span>
                                                </a>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


<script type="text/javascript">
if (jQuery.fn.owlCarousel) {
var autoplay = 7000,
smartSpeed_c = 700,
recently_slider = jQuery('.recently-slider');
//Hero_Slider_crsl

recently_slider.owlCarousel({
nav: true,
dots: false,
autoplay: true,
margin: 0,
lazyLoad: true,
loop: false,
items: 4,
//animation: true,
touchDrag:false,
mouseDrag:false,
//animateIn: 'fadeIn',
smartSpeed: smartSpeed_c,
autoplayTimeout: autoplay,
responsiveClass:true,
responsive:{
0:{
items:1,
margin:0
},
568:{
items:1,
margin: 0
},
640:{
items:2,
margin: 0
},
771:{
items:2,
margin: 0
},
1024:{
items:3,
margin: 0
},                    
1201:{
items:4,
margin:0
},
1341:{
items:4
} 
}
});
}         
</script>