<div class="import-export-tax-rates">
    <?php if (!$block->getIsReadonly()): ?>
        <div class="import-tax-rates">
            <?php if ($block->getUseContainer()): ?>
            <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ echo $block->getUrl('pospaper/tiers/remove') ?>" method="post" enctype="multipart/form-data">
                <?php endif; ?>
                <?php echo $block->getBlockHtml('formkey')?>
                <div class="fieldset admin__field">
                    <div class="admin__field-control">
                        <?php echo $block->getButtonHtml(__('Remove Pricing Tiers'), '', 'remove-tiers') ?>
                    </div>
                </div>
                <?php if ($block->getUseContainer()): ?>
            </form>
        <?php endif; ?>
            <script>
                require(['jquery', "mage/mage", "loadingPopup"], function(jQuery){
                    jQuery('#import-form').mage('form').mage('validation');
                    (function ($) {
                        $('.remove-tiers').click(function(e){
                            e.preventDefault();
                            if(window.confirm("<?= $block->escapeJs($block->escapeHtml(__('Are you sure you want to delete Pricing Tiers?'))) ?>")) {
                                $(this.form).submit();
                            }
                        });
                    })(jQuery);
                });
            </script>
        </div>
    <?php endif; ?>
</div>
