<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AdvancedLayeredNavigation
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk_layer_loader_bg"><span></span></div>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<div class="filter-current">
    <strong class="block-subtitle filter-current-subtitle"
            role="heading"
            aria-level="2"
            data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Now Shopping by') ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): 
                $value = $_filter->getValue();

                $currenturl = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
                if ($_filter->getName() != 'Price' && strpos($currenturl, '_'.$value.'_') !== false) {
                    $url = str_replace('_'.$value.'_', "_", $currenturl);
                } elseif ($_filter->getName() != 'Price' && strpos($currenturl, '_'.$value) !== false) {
                    $url = str_replace('_'.$value, "", $currenturl);
                } elseif ($_filter->getName() != 'Price' && strpos($currenturl, $value.'_') !== false) {
                    $url = str_replace($value.'_', "", $currenturl);
                } elseif($_filter->getName() == 'Category') {
                    $url = str_replace('cat='.$value, "", $currenturl);
                } else {
                    $url = $_filter->getRemoveUrl();
                }
        ?>
            <li class="item">
                
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <span class="wk-filter-action action previous" data-url="<?php /* @escapeNotVerified */ echo $url ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                    </span>
                    <span class="wk-filter-action action remove"
                       title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       data-url="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                        <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                        <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                    </span>
                <?php else: ?>
                    <span class="wk-filter-action action remove" data-url="<?php /* @escapeNotVerified */ echo $url ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                       <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
                        <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                    </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
<?php 
    $params["_use_rewrite"] = true;
    $data = json_encode(["url" => $block->getUrl('advancedlayerednavigation/index/setvalues'),
    "clearUrl" => $block->getUrl('*/*/*', $params)]);
?>
<script type="text/x-magento-init">
{
    "body": {
        "Webkul_AdvancedLayeredNavigation/js/layerednavigation": <?php echo $data ?>
    }
}
</script>
