<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AdvancedLayeredNavigation
 * @author    Webkul
 * @copyright Copyright (c) 2010-2018 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php if ($block->canShowBlock()): ?>
<?php
$enable_filter = null;
$all_filter_attributes = array();
$showfilter = false;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$filters = $block->getFilters();
if (isset($category)) {
    $enable_filter = $category->getData('att_sorting');
    $showfilter = $category->getData('com_model_display');
    $all_filter_attributes = explode(',', $enable_filter);
    $orderedFilters = array();
    if(!empty($all_filter_attributes)) {
        foreach($filters as $filter) {
            $key = array_search($filter->getId(), $all_filter_attributes);
            if($key !== false) {
                $orderedFilters[$key] = $filter;
            }
        }
        if(!empty($orderedFilters)) {
            ksort($orderedFilters);
            $filters = $orderedFilters;
        }
    }
}
?>
    <div class="block filter1" id="layered-filter-block" data-enabled-filters="<?php echo $enable_filter ?>">
        <div class="refine-search md">
            <strong><?php echo __('Refine Your Search') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <span data-url="<?php echo $block->getClearUrl() ?>" class="wk-filter-action action clear filter-clear">
                        <a href="#"><?php echo __('Clear All') ?></a>
                    </span>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($filters as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions) { ?>
                        <div class="filter-options" id="narrow-by-list" data-role="content">
                    <?php $wrapOptions = true;
                        } ?>
                    <?php if ($enable_filter) { ?>
                        <?php if (in_array($filter->getId(), $all_filter_attributes) || $filter->getName() == "Category") { ?>
                            <div data-role="collapsible" class="filter-options-item">
                                <div data-role="title" class="filter-options-title"><?php echo __($filter->getName()) ?></div>
                                <div data-role="content" class="filter-options-content"><?php echo $block->getChildBlock('renderer')->render($filter); ?></div>
                            </div>
                        <?php }
                    } else { ?>
                            <div data-role="collapsible" class="filter-options-item">
                                <div data-role="title" class="filter-options-title"><?php echo __($filter->getName()) ?></div>
                                <div data-role="content" class="filter-options-content"><?php echo $block->getChildBlock('renderer')->render($filter); ?></div>
                            </div>
                    <?php } ?>
                <?php endif; ?>
                <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    jQuery('ol.expandible').each(function () {
        var $ul = jQuery(this),
            $lis = $ul.find('li:gt(4)'),
            isExpanded = $ul.hasClass('expanded');
        $lis[isExpanded ? 'show' : 'hide']();

        if ($lis.length > 0) {
            $ul.append(jQuery('<span class="showmore"><p class="expand">' + (isExpanded ? 'Show Less' : 'Show More') + '</p></span>')
                .click(function (event) {
                    var isExpanded = $ul.hasClass('expanded');
                    event.preventDefault();
                    jQuery(this).html(isExpanded ? '<p class="expand">Show More</p>' : '<p class="expand">Show Less</p>');
                    $ul.toggleClass('expanded');
                    $lis.toggle();
                }));
        }
    });

    jQuery(document).ready(function () {
        jQuery(".filter-options-item").addClass("active");
        jQuery('.filter-options-title').click(function () {
            jQuery(this).parent().toggleClass('active');
        });
    });
</script>

<script type="text/javascript">
    if (jQuery(window).width() < 771) {
        jQuery('.refine-search.md').click(function () {
            jQuery(this).next().slideToggle();
            jQuery(this).parent().toggleClass('filter-title-active');
        });
    }
</script>
